sudo: required
services:
  - docker

before_install:
  - docker build -t darpham/docker-multi -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true darpham/docker-multi npm test

after_success:
  - docker build -t darpham/multi-client ./client
  - docker build -t darpham/multi-nginx ./nginx
  - docker build -t darpham/multi-server ./server
  - docker build -t darpham/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push darpham/multi-client
  - docker push darpham/multi-nginx
  - docker push darpham/multi-server
  - docker push darpham/multi-worker


deploy: 
  # edge: true
  provider: elasticbeanstalk
  region: us-west-1
  app: docker-multi-container
  env: DockerMultiContainer-env
  bucket: elasticbeanstalk-us-west-1-505221876540
  bucket_path: docker-multi-container
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY